### PR TITLE
Adding stats to Services and Destinations

### PR DESCRIPTION
**Pull request by luizbafilho**
This PR adds statistics to Services and Destinations

### CODE REVIEW

**Comment by mqliang** [comment]
@luizbafilho LGTM. Could you please rebase.

**Comment by luizbafilho** [comment]
@mqliang Done!

**Comment by mqliang** [comment]
@luizbafilho It seems that you merge the master branch into your own branch and submit a pull request, instead of rebasing. You could do a rebase as follows:

* `git remote add upstream https://github.com/mqliang/libipvs.git`
* `git remote update`
* `git checkout adding-statistics`
* `git rebase upstream/master`, (and solve conflicts if need)
* `git push -f origin adding-statistics`

**Comment by luizbafilho** [comment]
@mqliang thanks for instructions. Done.

**Comment by mqliang** [comment]
LGTM.

**Pull request merged**
